// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUhZDcjddZVO_CSTeRRw3nOxPkoLC0UoY',
    appId: '1:644048060968:android:7460dc8b548db777d42b1d',
    messagingSenderId: '644048060968',
    projectId: 'zouabi-org',
    storageBucket: 'zouabi-org.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_SYlWIo1vMFes83NlTZaAfVb0xqX0s9Y',
    appId: '1:644048060968:ios:155b40df6784b344d42b1d',
    messagingSenderId: '644048060968',
    projectId: 'zouabi-org',
    storageBucket: 'zouabi-org.appspot.com',
    iosBundleId: 'com.example.doft',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxNwEW5SV6pge9kdtt8kRPT6QWYRwRwiQ',
    appId: '1:644048060968:web:19c5b45549a1f2c0d42b1d',
    messagingSenderId: '644048060968',
    projectId: 'zouabi-org',
    authDomain: 'zouabi-org.firebaseapp.com',
    storageBucket: 'zouabi-org.appspot.com',
    measurementId: 'G-W9D2NFLB3Y',
  );

}